# Generated by Django 2.0.7 on 2018-07-16 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baoblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_time']},
        ),
    ]
