# Generated by Django 2.0.7 on 2018-07-17 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baoblog', '0006_auto_20180717_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Readnum',
        ),
    ]
