# Generated by Django 2.0.7 on 2018-07-17 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baoblog', '0008_readnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='blog',
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
