# Generated by Django 2.0.7 on 2018-07-20 09:21

import ckeditor_uploader.fields
import datetime
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('baoblog', '0010_remove_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=datetime.datetime(2018, 7, 20, 9, 21, 26, 605964, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
